//@version=5
indicator(title="Relative Strength Index Leader", shorttitle="RSIL", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
len = input.int(14, minval=1, title="Length")
src = input(close, "Source")
leader1 = input.int(1, title="leader 1")
leader2 = input.int(-1, title="leader 2")
rsi = ta.rsi(src,len)
manpulatedValue = src
manpulatedValue := barstate.isconfirmed? src : src + src*leader1/100
rsil1 = ta.rsi(manpulatedValue,len)
manpulatedValue := barstate.isconfirmed? src : src + src*leader2/100
rsil2 = ta.rsi(manpulatedValue,len)

plot(rsi, "RSI",linewidth=1, color=#7E57C2)
band1 = hline(70, "Upper Band", color=#787B86)
bandm = hline(50, "Middle Band", color=color.new(#787B86, 50))
band0 = hline(30, "Lower Band", color=#787B86)
fill(band1, band0, color=color.rgb(126, 87, 194, 90), title="Background")
plot(rsil1, "RSIL 1",linewidth=1, style=plot.style_line, color=barstate.isconfirmed? #7E57C2 : color.rgb(163, 159, 132, 60))
plot(rsil2, "RSIL 2",linewidth=1, style=plot.style_line, color=barstate.isconfirmed? #7E57C2 : color.rgb(163, 159, 132, 60))
